export { default as Navbar } from './Navbar';
export { default as Footer } from './Footer';
export { default as Hero } from './Hero';
export { default as Features } from './Features';
export { default as HowItWorks } from './HowItWorks';
export { default as HotelShowcase } from './HotelShowcase';
export { default as Testimonials } from './Testimonials';
export { default as CTA } from './CTA';
export { default as Blockchain } from './Blockchain';
